swagger: "2.0"
info:
  title: "Hello API"
  version: "1.0.0"
paths:
  /:
    get:
      responses:
        "200":
          description: "Successful response"
        "400":
          description: swagger generate server -f swagger.yaml"Bad request"